// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogger = "logger"

// Logger mapped from table <logger>
type Logger struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Level     string    `gorm:"column:level" json:"level"`
	TraceID   string    `gorm:"column:trace_id" json:"trace_id"`
	UserID    string    `gorm:"column:user_id" json:"user_id"`
	Tag       string    `gorm:"column:tag" json:"tag"`
	Message   string    `gorm:"column:message" json:"message"`
	Stack     string    `gorm:"column:stack" json:"stack"`
	Data      string    `gorm:"column:data" json:"data"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName Logger's table name
func (*Logger) TableName() string {
	return TableNameLogger
}
