// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Code        string    `gorm:"column:code" json:"code"`
	Name        string    `gorm:"column:name" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	Sequence    int64     `gorm:"column:sequence" json:"sequence"`
	Type        string    `gorm:"column:type" json:"type"`
	Path        string    `gorm:"column:path" json:"path"`
	Properties  string    `gorm:"column:properties" json:"properties"`
	Status      string    `gorm:"column:status" json:"status"`
	ParentID    string    `gorm:"column:parent_id" json:"parent_id"`
	ParentPath  string    `gorm:"column:parent_path" json:"parent_path"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
