// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gin-api-mono/internal/schema/accessor"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          string         `gorm:"column:id;primaryKey" json:"id"`
	Username    string         `gorm:"column:username" json:"username"`
	Name        string         `gorm:"column:name" json:"name"`
	Password    string         `gorm:"column:password" json:"password"`
	Phone       string         `gorm:"column:phone" json:"phone"`
	Email       string         `gorm:"column:email" json:"email"`
	Remark      string         `gorm:"column:remark" json:"remark"`
	Status      accessor.Color `gorm:"column:status" json:"status"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	UserProfile *UserProfile   `gorm:"foreignKey:user_id" json:"user_profile"`
	Role        []Role         `gorm:"foreignKey:id;joinForeignKey:role_id;joinReferences:user_id;many2many:user_role;references:id" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
