// Code generated by protoc-gen-go-error-generator. DO NOT EDIT.
// Version v1.0.0
package errcode

var (
	SUCCESS                      = &Error{Code: 0, Msg: "成功"}                 //成功
	UNKNOWN                      = &Error{Code: 100000, Msg: "服务器未知错误"}       //服务器未知错误
	RedisConnectError            = &Error{Code: 100001, Msg: "Redis 连接失败"}    //Redis 连接失败
	MySQLConnectError            = &Error{Code: 100002, Msg: "MySQL 连接失败"}    //MySQL 连接失败
	WriteConfigError             = &Error{Code: 100003, Msg: "写入配置文件失败"}      //写入配置文件失败
	BasicInternalServerErrorID   = &Error{Code: 200000, Msg: "内部服务器错误"}       //内部服务器错误
	BasicBadRequestID            = &Error{Code: 200001, Msg: "请求失败"}          //请求失败
	BasicUnauthorizedID          = &Error{Code: 200002, Msg: "签名信息错误"}        //签名信息错误
	BasicForbiddenID             = &Error{Code: 200003, Msg: "请求被禁止"}         //请求被禁止
	BasicNotFoundID              = &Error{Code: 200004, Msg: "资源不存在"}         //资源不存在
	BasicMethodNotAllowedID      = &Error{Code: 200005, Msg: "暂无访问权限"}        //暂无访问权限
	BasicTooManyRequestsID       = &Error{Code: 200006, Msg: "请求过多"}          //请求过多
	BasicRequestEntityTooLargeID = &Error{Code: 200007, Msg: "请求内容大小超过限制"}    //请求内容大小超过限制
	BasicConflictID              = &Error{Code: 200008, Msg: "发生冲突,请重试或合并更新"} //发生冲突,请重试或合并更新
	BasicRequestTimeoutID        = &Error{Code: 200009, Msg: "请求超时"}          //请求超时
	BasicParamBindErrorID        = &Error{Code: 200010, Msg: "参数信息错误"}        //参数信息错误
	BasicUrlSignErrorID          = &Error{Code: 200011, Msg: "参数签名错误"}        //参数签名错误
	BasicSocketConnectError      = &Error{Code: 200012, Msg: "Socket 未连接"}    //Socket 未连接
	BasicSocketSendError         = &Error{Code: 200013, Msg: "Socket 消息发送失败"} //Socket 消息发送失败
	FileBackgroundImageFailure   = &Error{Code: 200014, Msg: "获取背景图片失败"}      //获取背景图片失败
	AdminLoginFailure            = &Error{Code: 202001, Msg: "管理员不存在或者密码错误!"} //管理员不存在或者密码错误!
	AdminUserBan                 = &Error{Code: 202002, Msg: "管理员被禁用"}        //管理员被禁用
	AdminCreateError             = &Error{Code: 202003, Msg: "创建管理员失败"}       //创建管理员失败
	AdminDetailError             = &Error{Code: 202004, Msg: "获取个人信息失败"}      //获取个人信息失败
)

var (
	Msg = map[int32]*Error{
		0:      &Error{Code: 0, Msg: "成功"},
		100000: &Error{Code: 100000, Msg: "服务器未知错误"},
		100001: &Error{Code: 100001, Msg: "Redis 连接失败"},
		100002: &Error{Code: 100002, Msg: "MySQL 连接失败"},
		100003: &Error{Code: 100003, Msg: "写入配置文件失败"},
		200000: &Error{Code: 200000, Msg: "内部服务器错误"},
		200001: &Error{Code: 200001, Msg: "请求失败"},
		200002: &Error{Code: 200002, Msg: "签名信息错误"},
		200003: &Error{Code: 200003, Msg: "请求被禁止"},
		200004: &Error{Code: 200004, Msg: "资源不存在"},
		200005: &Error{Code: 200005, Msg: "暂无访问权限"},
		200006: &Error{Code: 200006, Msg: "请求过多"},
		200007: &Error{Code: 200007, Msg: "请求内容大小超过限制"},
		200008: &Error{Code: 200008, Msg: "发生冲突,请重试或合并更新"},
		200009: &Error{Code: 200009, Msg: "请求超时"},
		200010: &Error{Code: 200010, Msg: "参数信息错误"},
		200011: &Error{Code: 200011, Msg: "参数签名错误"},
		200012: &Error{Code: 200012, Msg: "Socket 未连接"},
		200013: &Error{Code: 200013, Msg: "Socket 消息发送失败"},
		200014: &Error{Code: 200014, Msg: "获取背景图片失败"},
		202001: &Error{Code: 202001, Msg: "管理员不存在或者密码错误!"},
		202002: &Error{Code: 202002, Msg: "管理员被禁用"},
		202003: &Error{Code: 202003, Msg: "创建管理员失败"},
		202004: &Error{Code: 202004, Msg: "获取个人信息失败"},
	}

	Msg_English = map[int32]*Error{
		0:      &Error{Code: 0, Msg: "successful"},
		100000: &Error{Code: 100000, Msg: "unknown error"},
		100001: &Error{Code: 100001, Msg: "redis connect error"},
		100002: &Error{Code: 100002, Msg: "mysql connect error"},
		100003: &Error{Code: 100003, Msg: "write config error"},
		200000: &Error{Code: 200000, Msg: "internal server error"},
		200001: &Error{Code: 200001, Msg: "bad request"},
		200002: &Error{Code: 200002, Msg: "unauthorized"},
		200003: &Error{Code: 200003, Msg: "forbidden"},
		200004: &Error{Code: 200004, Msg: "not found"},
		200005: &Error{Code: 200005, Msg: "method not allowed"},
		200006: &Error{Code: 200006, Msg: "too many requests"},
		200007: &Error{Code: 200007, Msg: "request entity too large"},
		200008: &Error{Code: 200008, Msg: "conflict"},
		200009: &Error{Code: 200009, Msg: "request timeout"},
		200010: &Error{Code: 200010, Msg: "param bind error"},
		200011: &Error{Code: 200011, Msg: "url sign error"},
		200012: &Error{Code: 200012, Msg: "socket connect error"},
		200013: &Error{Code: 200013, Msg: "Basic socket send error"},
		200014: &Error{Code: 200014, Msg: "filebackgroundimagefailure"},
		202001: &Error{Code: 202001, Msg: "The username does not exist or the password is incorrect"},
		202002: &Error{Code: 202002, Msg: "user is banned"},
		202003: &Error{Code: 202003, Msg: "admin create error"},
		202004: &Error{Code: 202004, Msg: "admin detail error"},
	}
)
